// Generated by ts-to-zod
import { z } from "zod";
import { type TTSObject } from "./types";

export const customDeckSchema = z.object({
  FaceURL: z.string(),
  BackURL: z.string(),
  NumWidth: z.number(),
  NumHeight: z.number(),
  BackIsHidden: z.boolean(),
  UniqueBack: z.boolean(),
});

export const ttsObjectSchema: z.ZodSchema<TTSObject> = z.lazy(() =>
  z.object({
    Name: z.string(),
    ChildObjects: z.array(ttsObjectSchema).optional(),
    ContainedObjects: z.array(ttsObjectSchema).optional(),
    CustomDeck: z.record(customDeckSchema).optional(),
  })
);

export const saveFileSchema = z.record(z.any()).and(
  z.object({
    SaveName: z.string(),
    ObjectStates: z.array(ttsObjectSchema),
  })
);
